---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: infrastructure
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/apps
  prune: true
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: cluster-secret-vars
  #     - kind: Secret
  #       name: cluster-user-auth
