---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/charts
  prune: true
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: cluster-secret-vars
