---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/namespaces
  prune: true
